Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

# Metrics/ClassLength:
#   Max: 120

Metrics/MethodLength:
  Max: 10
  Exclude:
  - lib/tasks/legacy.rake
  - test/**/*

AllCops:
  Exclude:
  - bin/*
  - db/**/*
  - vendor/**/*
  - Gemfile
  - Gemfile.lock
  - Rakefile
