language: ruby
rvm: 2.3.1
addons:
  postgresql: 9.4
cache:
- bundler
- apt
- directories:
  - tmp/cache/assets/test/sprockets
notifications:
  email: false
before_script:
- psql -c 'create database collection_test;' -U postgres
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: QeKTDjYKl28IBayCfpVPKNtHl1TI7vYCLrRlEkHF9cCOUhbGeKV7pK81C+7e5B23sSjiKMqOjhCLBUVHtlZFp4g2ad+y5oB5+kNa1vJE0FqosQY1h5jbjDN5q0s3/G1/IiXoEQ2LSeP4vD9jP9XpFE/SCF0+naL30mB1fwBuPjKrorjxeYyUkItfzui95ugdu1JqOZ0+tAculTHuLCPK3y/hM43t3uZAv0wiEgwlvggZli1to2zyFgii2mEkQic1Q4fPm+HVSmosyaAG6Z1TVQQqe4EgE91i3EWUnkJT1Y+smz/9xjVEVwlamsY21FZR1YEbII/7QXK4QZ4/66TfxyfnoSQwr6SwucU24zQAAZ9r6m3oSMbcDAy1/0K4x3ATcNV3HAUIsuN/EfikrW1ngOE7pspHrlsMesHE2MjrFYK3aID7Nw1p7U12xpxzo/KF1pabTlDVhphR55y14WDaAxdww7ibxJRbNrZxENYWEAo70XXpH9NOSnKIjUw7OAQb+8tNASIbk0Eqr+PnpLREHombnClTU1dsfb7QfZsntn9TGWLSpKlti7EEv/DRm4ptPV+OUg7QjZOwmapJo8+KZq92TPrC+IyVOjsN8cMlyVJCDBKKe5/P+RGTAn7Kxc09Iqua1HhrF6K/bHn4+Aw5TLttGKqALS/vzLj0T+j7N+k=
  app: hoggardwagner
  on:
    repo: bhoggard/collection
  run:
    - "rake db:migrate"
    - restart
