language: ruby
rvm: 2.2.3
addons:
  postgresql: 9.4
cache:
- bundler
- apt
- directories:
  - tmp/cache/assets/test/sprockets
notifications:
  email: false
before_script:
- psql -c 'create database collection_test;' -U postgres
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
