language: ruby
rvm: 2.3.3
addons:
  postgresql: 9.4
cache:
- bundler
- apt
- directories:
  - tmp/cache/assets/test/sprockets
notifications:
  email: false
before_script:
- psql -c 'create database collection_test;' -U postgres
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: iN5hBzfYfAiMiUPpqhGEFWALrX7tMtZlP1QeSfiGYdNeCd6JALGCW3soZn6lH2Ro/gnoy7++peHrCitOrm9vXpMaCvtQG4V4kBBKbxILyY9WLj/3VmqkgoRvU93TXVXZI8DFv5vOAwkM2XL0Miv8G+MG+/H1WFvHUGbgXwdhWnpSv/I2Iw+IaYqdl00BNeAWZ1W+H/ZV+J/8wsYvobwSiYzIrZcISkOFj3lZbj/dtbhsf/4MlzXsxzhLj2bQ8aifHDj+73jd0VFyqGNwAtMQ7FL6sD/iR0UTCV/4dY53B0yQtanU+Hgyoq9l9LV4ZAGqdv44Co3OdsH10YoA4Ou649O6qDiwM2XmNEweQxTirrDWlDEZvgigUuN0+6b4X8FGw3hi3vGMoEbyYcrMW4+ju0MDUw5RDbmrFeRXxkIcn2/QzxyVoY0ElE6NsLr+mLKwEskTGfFS5CN5BzDGD9FIaimsD79lygqu8U74yNBnU/HixgnFryBiRDBzmNGGOr9OqoyA7gkbEQqs8x/slK6HrIe90PYWyZSNOxQE2Zu7FyHfLWHNfjEunLyTaf1+nHsGDXqBYVDmpGT0lwiAbTmjcVW/jdYk/uJg+Osn59Sx9UTcaWQXpuvUutCAEefUgt0Npp/KuhS2dA740U/2ikkj1SPNyUGNWmMMdaXNX189XBA=
  app: hoggardwagner
  on:
    repo: bhoggard/collection
  run:
  - rake db:migrate
  - restart
