# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808a38404a3efd73613446c6271931f0834a54d2a99a14420c68d57fe959157fec9eb260ca949ff4016c68d43e4a322d4f1abc23aaf5db11d8f9fcfab5a90528
  image_secret: <%= ENV["IMAGE_SECRET"] %>
  contact_email: <%= ENV["CONTACT_EMAIL"] %>
  cdn_url: <%= ENV["AWS_CDN"] %>

test:
  secret_key_base: 0502ee50dc34e241c8bf5b347b3365ae3e990c6ed46e674016399d91a608207e3467694a8f871dc595539ce18573d5c3f82d441310a43bb969e21266616a6927
  image_secret: abcdef
  contact_email: "me@example.com,you@google.com"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  image_secret: <%= ENV["IMAGE_SECRET"] %>
  contact_email: <%= ENV["CONTACT_EMAIL"] %>
  cdn_url: <%= ENV["AWS_CDN"] %>
